development:
  clients:
    default:
      database: the_resistance_development
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: the_resistance_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%=ENV['MONGOID_URI']%>
  options:
    raise_not_found_error: false
