development:
  clients:
    default:
      uri: mongodb+srv://the_resistance:<%= ENV['MONGOID_PASSWORD'] %>@the-resistance-mongo.vsvu7pz.mongodb.net/?retryWrites=true&w=majority
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: the_resistance_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: mongodb+srv://the_resistance:<%= ENV['MONGOID_PASSWORD'] %>@the-resistance-mongo.vsvu7pz.mongodb.net/?retryWrites=true&w=majority
  options:
    raise_not_found_error: false
